import {test} from 'node:test';import assert from 'node:assert/strict';
import {calculateDueDate,getCurrentDateStr} from '../src/utils/dateUtils';
import {enrichObligation,getMonthSummary,matrixMonth,type Snapshot} from '../src/domain';
const db:Snapshot={cards:[{id:'c',userId:'u',name:'Thử',bankName:'A',defaultDueDay:1,status:'active',autoWeekendShift:true,startTrackingMonth:'2026-01',createdAt:'',updatedAt:''}],obligations:[{id:'o',userId:'u',cardId:'c',month:'2026-02',dataState:'DECLARED',amount:5000000,dueDay:30,actualDueDate:'2026-01-30',dueDateSource:'WEEKEND_FRIDAY_SUGGESTION',isEstimatedDue:false,firstDeclaredAt:null,noExpenseConfirmedAt:null,updateReminderDate:'2026-01-23',updateReminderSource:'DEFAULT_7_DAYS',updateReminderReason:'',createdAt:'',updatedAt:''}],payments:[{id:'p',userId:'u',obligationId:'o',cardId:'c',amount:2000000,paidDate:'2026-03-01',createdAt:'',status:'VALID'}],auditLogs:[],notifications:[],config:{userId:'u',dailyDigestTime:'08:00',emailEnabled:false,targetEmail:'',discreteMode:false}};
test('khác biệt nghĩa vụ kỳ và dòng tiền thực chi',()=>{const feb=getMonthSummary(db,'u','2026-02'),mar=getMonthSummary(db,'u','2026-03');assert.equal(feb.totalPaidForMonthObligations,2000000);assert.equal(feb.actualCashflowPaidInMonth,0);assert.equal(mar.actualCashflowPaidInMonth,2000000);assert.equal(mar.priorUnpaidObligations[0].remainingAmount,3000000);});
test('không xếp hạn tháng trước vào ngày 30 của tháng nghĩa vụ',()=>{const m=matrixMonth(db,'u',2026,2);assert.equal(m.rows[0].obligation!.actualDueDate,'2026-01-30');assert.ok(Object.values(m.dailyTotals).every((t:any)=>t.cardCount===0));});
test('ngày cuối tháng, năm nhuận và dời cuối tuần',()=>{assert.equal(calculateDueDate(2028,2,31).actualDueDate,'2028-02-29');assert.equal(calculateDueDate(2026,2,1,true).actualDueDate,'2026-01-30');});
test('ngày Việt Nam độc lập múi giờ máy',()=>{const expected=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());for(const tz of ['UTC','Asia/Ho_Chi_Minh','America/New_York']){process.env.TZ=tz;assert.equal(getCurrentDateStr(),expected);}});
test('trạng thái thanh toán và không phát sinh',()=>{assert.equal(enrichObligation(db,db.obligations[0],'u').paymentStatus,'PARTIAL');assert.equal(enrichObligation(db,{...db.obligations[0],dataState:'UNUPDATED',amount:0},'u').paymentStatus,'UNDETERMINED');assert.equal(enrichObligation(db,{...db.obligations[0],dataState:'NO_EXPENSE',amount:0},'u').paymentStatus,'NOT_APPLICABLE');});
