import React,{useEffect,useState} from 'react';
import {api} from '../api';
import {supabase} from '../supabase';
import type {UserConfig,AuditLog} from '../types';
interface Props{config:UserConfig;onUpdateConfig:(cfg:Partial<UserConfig>)=>Promise<void>}
export function SettingsAndTestsTab({config,onUpdateConfig}:Props){
 const [time,setTime]=useState(config.dailyDigestTime||'08:00'),[email,setEmail]=useState(config.targetEmail||''),[enabled,setEnabled]=useState(config.emailEnabled||false),[logs,setLogs]=useState<AuditLog[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[password,setPassword]=useState('');
 useEffect(()=>{setTime(config.dailyDigestTime);setEmail(config.targetEmail||'');setEnabled(config.emailEnabled);},[config]);
 useEffect(()=>{api.getAuditLogs().then(setLogs).catch(e=>setMessage(e.message));},[]);
 async function run(fn:()=>Promise<any>){setBusy(true);setMessage('');try{await fn();setLogs(await api.getAuditLogs());}catch(e:any){setMessage('Lỗi: '+e.message);}finally{setBusy(false);}}
 return <div className="space-y-6">
 <section className="bg-white p-6 rounded-2xl border border-slate-200"><h2 className="font-bold text-lg">Lịch nhắc và email</h2><p className="text-sm text-slate-600 mt-2">Thông báo trong ứng dụng được tạo theo lịch nếu đã chạy tệp 02_BAT_LICH_NHAC.sql. Email chỉ gửi sau khi cấu hình dịch vụ gửi email theo hướng dẫn nâng cao; bật công tắc này chỉ đưa bản tin vào hàng đợi.</p>
 <div className="grid sm:grid-cols-2 gap-4 mt-5"><label>Giờ tổng hợp mỗi ngày (giờ Việt Nam)<input aria-label="Giờ nhắc" className="block border rounded-lg p-2 mt-2" type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>Email nhận bản tin<input aria-label="Email nhận" className="block border rounded-lg p-2 mt-2 w-full" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label></div>
 <label className="block mt-4"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Đưa bản tin vào hàng đợi email</label>
 <div className="flex flex-wrap gap-3 mt-4"><button disabled={busy} className="bg-indigo-600 text-white rounded-lg px-4 py-2 disabled:opacity-50" onClick={()=>run(async()=>{await onUpdateConfig({dailyDigestTime:time,emailEnabled:enabled,targetEmail:email});setMessage('Đã lưu cấu hình.');})}>Lưu cài đặt</button><button disabled={busy} className="border rounded-lg px-4 py-2" onClick={()=>run(async()=>{const r=await api.triggerReminderCheck();setMessage(`Đã kiểm tra, tạo ${r.generatedCount} thông báo mới.`);window.dispatchEvent(new CustomEvent('app:data_changed'));})}>Kiểm tra nhắc hạn ngay</button></div></section>
 <section className="bg-white p-6 rounded-2xl border border-slate-200"><h2 className="font-bold text-lg">Sao lưu và khôi phục</h2><p className="text-sm text-slate-600 mt-2">Sao lưu gồm thẻ, nghĩa vụ, các lần thanh toán và cài đặt. Khôi phục thay thế dữ liệu hiện tại; lịch sử thao tác hiện tại vẫn được giữ. Chỉ nhận định dạng sao lưu phiên bản Supabase này.</p><div className="flex flex-wrap gap-3 mt-4"><button disabled={busy} className="border rounded-lg px-4 py-2" onClick={()=>run(async()=>{await api.exportBackup();setMessage('Đã tải tệp sao lưu.');})}>Tải sao lưu JSON</button><label className="border rounded-lg px-4 py-2 cursor-pointer">Khôi phục JSON<input disabled={busy} type="file" accept=".json" className="hidden" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(!confirm('Khôi phục sẽ thay thế các thẻ, nghĩa vụ và giao dịch hiện tại. Anh đã sao lưu và muốn tiếp tục?'))return;await run(async()=>{if(f.size>10000000)throw new Error('Tệp vượt giới hạn 10 MB');await api.importBackup(JSON.parse(await f.text()));window.dispatchEvent(new CustomEvent('app:data_changed'));window.location.reload();});}}/></label></div></section>
 <section className="bg-white p-6 rounded-2xl border border-slate-200"><h2 className="font-bold text-lg">Đổi mật khẩu</h2><input aria-label="Mật khẩu mới" type="password" autoComplete="new-password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mật khẩu mới từ 12 ký tự" className="border rounded-lg p-2 mt-4 w-full max-w-sm"/><button disabled={busy} className="border rounded-lg px-4 py-2 ml-3" onClick={()=>run(async()=>{if(password.length<12)throw new Error('Mật khẩu cần ít nhất 12 ký tự');const {error}=await supabase.auth.updateUser({password});if(error)throw error;setPassword('');setMessage('Đã đổi mật khẩu.');})}>Đổi mật khẩu</button></section>
 {message&&<p role="status" className="p-4 bg-indigo-50 text-indigo-900 rounded-xl">{message}</p>}
 <section className="bg-white p-6 rounded-2xl border border-slate-200"><h2 className="font-bold text-lg mb-4">Lịch sử thay đổi (500 thao tác gần nhất)</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th className="p-2">Thời điểm</th><th className="p-2">Đối tượng</th><th className="p-2">Thao tác</th><th className="p-2">Lý do</th></tr></thead><tbody>{logs.map(l=><tr key={l.id} className="border-t"><td className="p-2">{new Date(l.createdAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}</td><td className="p-2">{l.entityType}</td><td className="p-2">{l.action}</td><td className="p-2">{l.reason}</td></tr>)}</tbody></table>{!logs.length&&<p className="text-slate-500">Chưa có thao tác thay đổi.</p>}</div></section>
 </div>;
}
