import React,{useEffect,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {supabase,configured} from './supabase';
import {App} from './App';
export function AuthGate(){
 const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let live=true;supabase.auth.getSession().then(({data,error})=>{if(live){setSession(data.session);setLoading(false);if(error)setError(error.message);}});const {data}=supabase.auth.onAuthStateChange((_,s)=>{if(live){setSession(s);setLoading(false);}});return()=>{live=false;data.subscription.unsubscribe();};},[]);
 if(!configured)return <div className="max-w-xl mx-auto mt-20 p-8 bg-white rounded-2xl shadow"><h1 className="text-xl font-bold">Chưa nhập thông tin kết nối</h1><p className="mt-4">Trong Vercel, nhập VITE_SUPABASE_URL và VITE_SUPABASE_PUBLISHABLE_KEY, sau đó triển khai lại (Redeploy). Không dùng Secret key.</p></div>;
 if(loading)return <p className="text-center mt-20">Đang kiểm tra đăng nhập...</p>;
 if(session)return <div key={session.user.id}><div className="bg-indigo-950 text-white px-4 py-2 flex flex-wrap gap-2 justify-between text-sm"><span>{session.user.email}</span><button onClick={async()=>{const {error}=await supabase.auth.signOut();if(error)alert(error.message);}}>Đăng xuất</button></div><App/></div>;
 const login=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;}catch(e:any){setError(e.message==='Invalid login credentials'?'Email hoặc mật khẩu chưa đúng.':e.message);}finally{setBusy(false);}};
 return <div className="min-h-screen bg-gradient-to-br from-indigo-100 via-white to-blue-100 flex items-center justify-center p-4"><form onSubmit={login} className="bg-white shadow-xl rounded-3xl p-8 w-full max-w-md"><h1 className="text-2xl font-bold text-indigo-950">Sổ thanh toán thẻ</h1><p className="text-slate-500 mt-2 mb-7">Đăng nhập để quản lý dữ liệu của anh.</p><label className="block text-sm font-medium">Email<input aria-label="Email" type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} className="block w-full border rounded-xl p-3 mt-2 mb-5"/></label><label className="block text-sm font-medium">Mật khẩu<input aria-label="Mật khẩu" type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="block w-full border rounded-xl p-3 mt-2 mb-5"/></label>{error&&<p role="alert" className="text-red-700 mb-4">{error}</p>}<button disabled={busy} className="w-full bg-indigo-600 text-white rounded-xl p-3 font-semibold disabled:opacity-50">{busy?'Đang đăng nhập...':'Đăng nhập'}</button><p className="text-xs text-slate-500 mt-5">Tài khoản được tạo trong Supabase → Authentication → Users. Xem hướng dẫn đi kèm bộ cài đặt.</p></form></div>;
}
